name: 'Generate Contribution Badges'
description: 'Fetch commit count, PR count, last commit, and generate customizable shields badges.'
author: 'André Bastos Dias'
inputs:
  user:
    description: 'GitHub username to generate badges for'
    required: true
  repository:
    description: 'Owner/repo to query (default is current repo)'
    required: false
    default: '${{ github.repository }}'
  colors:
    description: 'Comma-separated colors for badges: contributor,commits,open_prs,last_commit'
    required: false
    default: 'blue,green,orange,red'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run badge generator
      shell: bash
      env:
        USER: ${{ inputs.user }}
        REPO: ${{ inputs.repository }}
        COLORS: ${{ inputs.colors }}
      run: |
        scripts/generate.sh
    - name: Check for changes and commit
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/

        if git diff --cached --quiet; then
          echo "No changes to commit"
          exit 0
        fi

        COMMIT_MESSAGE="Update badges"
        [[ "${GITHUB_EVENT_NAME:-}" == "schedule" ]] && COMMIT_MESSAGE+=" ($(date +'%Y-%m-%d %H:00'))"

        git commit -m "${COMMIT_MESSAGE}"
        git push
