name: generate-contribution-badges

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00.
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  badges:
    runs-on: ubuntu-latest
    env:
      USER: andrebastosdias
      REPO: smogon/pokemon-showdown
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run badge generator
        uses: ./
        with:
          user: ${{ env.USER }}
          repository: ${{ env.REPO }}
