name: generate-contribution-badges

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  USER: andrebastosdias

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout self
        uses: actions/checkout@v4

      - name: Fetch contributor data
        run: |
          curl -s https://api.github.com/repos/smogon/pokemon-showdown/contributors?per_page=100 > contributors.json

      - name: Extract commit count and rank
        id: commit_and_rank
        run: |
          COMMITS=$(jq ".[] | select(.login == \"$USER\") | .contributions" contributors.json)
          POS=$(jq -r ".[] | .login" contributors.json | grep -n "^$USER$" | cut -d: -f1)
          RANK=$(( POS + 1 ))
          echo "commits=$COMMITS" >> $GITHUB_OUTPUT
          echo "rank=$RANK" >> $GITHUB_OUTPUT

      - name: Fetch number of open non-draft PRs by me
        id: open_prs
        run: |
          OPEN_PRS=$(curl -s "https://api.github.com/search/issues?q=repo:smogon/pokemon-showdown+is:pr+is:open+draft:false+author:${USER}" \
            | jq '.total_count')
          echo "open_prs=$OPEN_PRS" >> $GITHUB_OUTPUT

      - name: Fetch my last commit timestamp
        id: lastcommit_ts
        run: |
          TIMESTAMP=$(curl -s "https://api.github.com/repos/smogon/pokemon-showdown/commits?author=$USER&per_page=1" \
            | jq -r '.[0].commit.committer.date')
          UNIX_TS=$(date -d "$TIMESTAMP" +%s)
          echo "ts=$UNIX_TS" >> $GITHUB_OUTPUT

      - name: Fetch my last commit message
        id: lastcommit_msg
        run: |
          MSG=$(curl -s "https://api.github.com/repos/smogon/pokemon-showdown/commits?author=$USER&per_page=1" \
            | jq -r '.[0].commit.message' | head -n1 | sed 's/"/\\"/g')
          echo "msg=$MSG" >> $GITHUB_OUTPUT

      - name: Generate badge SVGs
        run: |
          mkdir -p docs
          C=${{ steps.commit_and_rank.outputs.commits }}
          R_ESC=$(printf '%s' "${{ steps.commit_and_rank.outputs.rank }}" | sed 's/^/%23/')
          PR=${{ steps.open_prs.outputs.open_prs }}
          TS=${{ steps.lastcommit_ts.outputs.ts }}
          # M=${{ steps.lastcommit_msg.outputs.msg }}
          # M_ESC=$(python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1]))" "${M}")

          curl -s "https://img.shields.io/static/v1?label=commits&message=${C}&color=F34134&style=flat" \
            > docs/commits.svg
          curl -s "https://img.shields.io/static/v1?label=contributor&message=${R_ESC}&color=8334B7&style=flat" \
            > docs/contributor.svg
          curl -s "https://img.shields.io/static/v1?label=open%20pull%20requests&message=${PR}&color=00A398&style=flat" \
            > docs/open-pull-requests.svg
          curl -s "https://img.shields.io/date/${TS}.svg?label=last%20commit&color=004878&style=flat" \
            > docs/last-commit.svg
          # curl -s "https://img.shields.io/static/v1?label=last%20commit&message=${M_ESC}&color=004878&style=flat" \
          #   > docs/last-commit.svg

      - name: Add .nojekyll
        run: touch docs/.nojekyll

      - name: Commit and push badges
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add docs/
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            DATE=$(date +"%d %b %Y")
            git commit -m "Update badges - $DATE" || echo "No changes to commit"
          else
            git commit -m "Update badges" || echo "No changes to commit"
          fi
          git push
