name: generate-contribution-badges

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  USER: andrebastosdias

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout self
        uses: actions/checkout@v4

      - name: Extract commit count and rank
        id: commit_and_rank
        run: |
          DATA=$(curl -s https://api.github.com/repos/smogon/pokemon-showdown/stats/contributors)
          TOTAL=$(echo "$DATA" | jq length)
          INDEX=$(echo "$DATA" | jq -r '.[].author.login' | grep -n "^$USER$" | cut -d: -f1)
          if [[ -z "$INDEX" ]]; then
            echo "User not found in contributors list."
            COMMITS=0
            RANK="N/A"
          else
            INDEX=$((INDEX - 1))
            RANK=$((TOTAL - INDEX))
            COMMITS=$(echo "$DATA" | jq ".[$INDEX].total")
          fi
          echo "commits=$COMMITS" >> $GITHUB_OUTPUT
          echo "rank=$RANK" >> $GITHUB_OUTPUT

      - name: Fetch number of open non-draft PRs by me
        id: open_prs
        run: |
          OPEN_PRS=$(curl -s "https://api.github.com/search/issues?q=repo:smogon/pokemon-showdown+is:pr+is:open+draft:false+author:${USER}" \
            | jq '.total_count')
          echo "open_prs=$OPEN_PRS" >> $GITHUB_OUTPUT

      - name: Fetch my last commit timestamp
        id: lastcommit_ts
        run: |
          TIMESTAMP=$(curl -s "https://api.github.com/repos/smogon/pokemon-showdown/commits?author=$USER&per_page=1" \
            | jq -r '.[0].commit.committer.date')
          UNIX_TS=$(date -d "$TIMESTAMP" +%s)
          echo "ts=$UNIX_TS" >> $GITHUB_OUTPUT

      - name: Fetch my last commit message
        id: lastcommit_msg
        run: |
          RAW_MSG=$(curl -s "https://api.github.com/repos/smogon/pokemon-showdown/commits?author=$USER&per_page=1" \
            | jq -r '.[0].commit.message' | head -n1 | sed 's/"/\\"/g')
          MSG=$(echo "$RAW_MSG" | sed 's/([^)]*)//g' | xargs)
          echo "msg=$MSG" >> $GITHUB_OUTPUT

      - name: Assert numeric outputs
        run: |
          is_number() {
            echo "$1" | grep -Eq '^[0-9]+$'
          }

          C=${{ steps.commit_and_rank.outputs.commits }}
          R=${{ steps.commit_and_rank.outputs.rank }}
          PR=${{ steps.open_prs.outputs.open_prs }}
          TS=${{ steps.lastcommit_ts.outputs.ts }}

          for var_name in C R PR TS; do
            val=${!var_name}
            if ! is_number "$val"; then
              echo "❌ Error: $var_name is not a valid number ('$val')"
              exit 1
            fi
          done

          echo "✅ All values are valid numbers."

      - name: Generate badge SVGs
        run: |
          mkdir -p docs
          C=${{ steps.commit_and_rank.outputs.commits }}
          R_ESC=$(printf '%s' "${{ steps.commit_and_rank.outputs.rank }}" | sed 's/^/%23/')
          PR=${{ steps.open_prs.outputs.open_prs }}
          TS=${{ steps.lastcommit_ts.outputs.ts }}
          M="${{ steps.lastcommit_msg.outputs.msg }}"

          REL_TIME=$(curl -s "https://img.shields.io/date/${TS}.json" | jq -r '.value')
          COMBINED="${REL_TIME} | ${M}"
          COMBINED_ESC=$(python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1]))" "$COMBINED")

          curl -s "https://img.shields.io/static/v1?label=contributor&message=${R_ESC}&color=F34134&style=flat" \
            > docs/contributor.svg
          curl -s "https://img.shields.io/static/v1?label=commits&message=${C}&color=8334B7&style=flat" \
            > docs/commits.svg
          curl -s "https://img.shields.io/static/v1?label=open%20pull%20requests&message=${PR}&color=00A398&style=flat" \
            > docs/open-pull-requests.svg
          curl -s "https://img.shields.io/static/v1?label=last%20commit&message=${COMBINED_ESC}&color=004878&style=flat" \
            > docs/last-commit.svg

      - name: Add .nojekyll
        run: touch docs/.nojekyll

      - name: Commit and push badges
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add docs/
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            DATE=$(date +"%d %b %Y")
            git commit -m "Update badges - $DATE" || echo "No changes to commit"
          else
            git commit -m "Update badges" || echo "No changes to commit"
          fi
          git push
