name: Generate Contribution Badges

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout self
        uses: actions/checkout@v3

      - name: Fetch contributor data
        run: |
          curl -s https://api.github.com/repos/smogon/pokemon-showdown/contributors?per_page=100 > contributors.json

      - name: Extract commit count and rank (with +1)
        id: extract
        run: |
          USER="andrebastosdias"
          # get raw values
          RAW_COMMITS=$(jq ".[] | select(.login == \"$USER\") | .contributions" contributors.json)
          RAW_POS=$(jq -r ".[] | .login" contributors.json | grep -n "^$USER$" | cut -d: -f1)

          # add 1 to each (default to zero if missing)
          COMMITS=$(( RAW_COMMITS + 1 ))
          POS=$(( RAW_POS + 1 ))

          echo "commits=$COMMITS" >> $GITHUB_OUTPUT
          echo "rank=$POS" >> $GITHUB_OUTPUT

      - name: Create static shields.io badge URLs
        run: |
          mkdir -p docs
          echo "https://img.shields.io/badge/commits-$(( ${{ steps.extract.outputs.commits }} ))-blue" > docs/commits.txt
          echo "https://img.shields.io/badge/contributor-$(( ${{ steps.extract.outputs.rank }} ))-blue" > docs/contributor.txt

      - name: Add .nojekyll
        run: touch docs/.nojekyll

      - name: Commit and push badges
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          DATE=$(date +"%d %b %Y")
          git add docs/commits.txt docs/contributor.txt docs/.nojekyll
          git commit -m "Update badges - $DATE" || echo "No changes"
          git push
