name: generate-contribution-badges

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  badges:
    runs-on: ubuntu-latest

    env:
      USER: andrebastosdias
      REPO: smogon/pokemon-showdown
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run badge generator
        uses: ./
        with:
          user: ${{ env.USER }}
          repository: ${{ env.REPO }}
