name: generate-contribution-badges

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout self
        uses: actions/checkout@v4

      - name: Fetch contributor data
        run: |
          curl -s https://api.github.com/repos/smogon/pokemon-showdown/contributors?per_page=100 > contributors.json

      - name: Extract commit count and rank (with +1)
        id: extract
        run: |
          USER="andrebastosdias"
          # get raw values
          RAW_COMMITS=$(jq ".[] | select(.login == \"$USER\") | .contributions" contributors.json)
          RAW_POS=$(jq -r ".[] | .login" contributors.json | grep -n "^$USER$" | cut -d: -f1)

          # add 1 to each (default to zero if missing)
          COMMITS=$(( RAW_COMMITS + 1 ))
          POS=$(( RAW_POS + 1 ))

          echo "commits=$COMMITS" >> $GITHUB_OUTPUT
          echo "rank=$POS" >> $GITHUB_OUTPUT

      - name: Generate Shields.io-style badge SVGs
        run: |
          mkdir -p docs
          COMMITS=${{ steps.extract.outputs.commits }}
          RANK_ESCAPED=$(printf '%s' "${{ steps.extract.outputs.rank }}" | sed 's/^/%23/')
          curl -s "https://img.shields.io/static/v1?label=commits&message=${COMMITS}&color=F34134" \
            > docs/commits.svg
          curl -s "https://img.shields.io/static/v1?label=contributor&message=%23${RANK_ESCAPED}&color=8334B7" \
            > docs/contributor.svg

      - name: Add .nojekyll
        run: touch docs/.nojekyll

      - name: Commit and push badges
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          DATE=$(date +"%d %b %Y")
          git add docs/
          git commit -m "Update badges - $DATE" || echo "No changes"
          git push
